apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-education-rocks-goapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-education-rocks-goapi
  template:
    metadata:
      labels:
        app: code-education-rocks-goapi
    spec:
      containers:
        - name: app
          image: marcusbalbi/code-education-go-api:latest
          ports:
            - containerPort: 8000
